name: Caching 
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    
    - name: Cache Primes 
      id: cache-primes 
      uses: actions/cache@v3 
      with: 
       path: primes 
       key: $ {{runner.os }}-primes
       
    - name: Generate prime Numbers 
      if: steps.cache-primes.outputs.cache—hit != 'true' 
      run: |
       sleep 60
       echo "1 2 3..." > primes
    - name: Use Prime Numbers 
      run: cat primes 

